version: 2.1

executors:
  docker-node:
    docker:
      - image: cimg/node:18.20  # Use a Node.js version compatible with your project

jobs:
  build-and-push:
    executor: docker-node

    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.18

      - run:
          name: Extract tag name
          command: |
            TAG_NAME=$(git describe --tags --abbrev=0)
            echo "export TAG_NAME=$TAG_NAME" >> $BASH_ENV

      - run:
          name: Build Docker image
          command: |
            source $BASH_ENV
            docker build -t $DOCKERHUB_USER/my-node-app:$TAG_NAME .

      - run:
          name: Push Docker image to Docker Hub
          command: |
            source $BASH_ENV
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
            docker push $DOCKERHUB_USER/my-node-app:$TAG_NAME

workflows:
  version: 2
  build-and-push-workflow:
    jobs:
      - build-and-push:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*$/
            branches:
              ignore: /.*/
