name: Docker Image CI
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set image tag from Git tag
      run: echo "TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tharinduakalanak/bus-route:$TAG
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "tharinduakalanak" --password-stdin
    - name: push image to docker hub
      run: docker push tharinduakalanak/bus-route:$TAG
